In [9]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

In [2]:
cd data

C:\Users\mery-\Desktop\Development\machine-learning-with-python\data


In [15]:
wine = pd.read_csv("wine.csv")
wine.head(5)

Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  Total phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   Flavanoids  Nonflavanoid phenols  Proanthocyanins  Color intensity   Hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   OD280/OD315 of diluted wines  Proline Wine Type  
0                          3.92   1065.0       One  
1                          3.40   1050.0       One  
2                          3.17   1185.0       One  
3                          3.45   1480.0       One  
4                          2.93    735.0       One

In [4]:
wine["Wine Type"].unique()

array(['One', 'Two', 'Three'], dtype=object)

In [5]:
wine["Wine Type"].value_counts()

Two      71
One      59
Three    48
Name: Wine Type, dtype: int64

In [7]:
x = wine.drop("Wine Type", axis=1)
y = wine["Wine Type"]

In [8]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

In [10]:
tree = DecisionTreeClassifier()
tree.fit(x_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [16]:
predictions = tree.predict(x_test)
predictions

array(['Three', 'Two', 'Three', 'Three', 'One', 'Three', 'Two', 'Three',
       'Two', 'Three', 'One', 'One', 'Three', 'One', 'Two', 'Two',
       'Three', 'Three', 'Three', 'One', 'Two', 'Two', 'One', 'Two',
       'One', 'One', 'Two', 'Three', 'One', 'Three', 'One', 'One', 'Two',
       'Three', 'Three', 'One', 'Two', 'One', 'One', 'Three', 'Two',
       'One', 'Three', 'One', 'Two', 'Two', 'Two', 'Three', 'Three',
       'Three', 'Two', 'Two', 'Three', 'Three'], dtype=object)

In [13]:
print(confusion_matrix(y_test, predictions))

[[14  0  0]
 [ 0 20  2]
 [ 2  1 15]]


In [14]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

         One       0.88      1.00      0.93        14
       Three       0.95      0.91      0.93        22
         Two       0.88      0.83      0.86        18

   micro avg       0.91      0.91      0.91        54
   macro avg       0.90      0.91      0.91        54
weighted avg       0.91      0.91      0.91        54

