## **Working with Numpy lists**

In [1]:
import numpy as np

In [2]:
numbers = [1,2,3,4]
numpy_array = np.array(numbers)
numpy_array

array([1, 2, 3, 4])

In [3]:
numbers_lists = [[1,2,3], [4,5,6], [7,8,9]]
numpy_matrix = np.array(numbers_lists)
numpy_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## **Arange, zeros, ones, linspace, eye**

**Arange()**

In [7]:
array = np.arange(5)
array

array([0, 1, 2, 3, 4])

In [8]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(2,20,3)

array([ 2,  5,  8, 11, 14, 17])

**zeros() and ones()**

In [15]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((3,4)) # Rows, Columns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.ones(3)

array([1., 1., 1.])

In [17]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

**linspace()**

In [18]:
np.linspace(5,8,50) # array with 50 elements. Values from 5 to 8

array([5.        , 5.06122449, 5.12244898, 5.18367347, 5.24489796,
       5.30612245, 5.36734694, 5.42857143, 5.48979592, 5.55102041,
       5.6122449 , 5.67346939, 5.73469388, 5.79591837, 5.85714286,
       5.91836735, 5.97959184, 6.04081633, 6.10204082, 6.16326531,
       6.2244898 , 6.28571429, 6.34693878, 6.40816327, 6.46938776,
       6.53061224, 6.59183673, 6.65306122, 6.71428571, 6.7755102 ,
       6.83673469, 6.89795918, 6.95918367, 7.02040816, 7.08163265,
       7.14285714, 7.20408163, 7.26530612, 7.32653061, 7.3877551 ,
       7.44897959, 7.51020408, 7.57142857, 7.63265306, 7.69387755,
       7.75510204, 7.81632653, 7.87755102, 7.93877551, 8.        ])

**eye()**

In [19]:
np.eye(5) # 2 dimensions matrix 5x5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## **Random Numbers**

In [20]:
np.random.rand(5) # only positive values

array([0.19971496, 0.59484571, 0.68490694, 0.38504413, 0.68645686])

In [22]:
np.random.rand(5,5) # multimentional array

array([[0.60230484, 0.1283873 , 0.46602909, 0.97575018, 0.30416552],
       [0.05640312, 0.84650955, 0.75363238, 0.90481419, 0.9443473 ],
       [0.72372779, 0.60947304, 0.26798521, 0.19730607, 0.75015022],
       [0.24544779, 0.42603279, 0.0481695 , 0.79983947, 0.43620751],
       [0.92290619, 0.70088957, 0.07555368, 0.36269904, 0.31287188]])

In [23]:
np.random.randn(5)  # positive and negative values

array([ 0.30529862,  0.0876923 ,  0.83407687, -1.02188107,  0.49703645])

In [27]:
np.random.randint(5,20) # One random number between 5 to 20

10

In [28]:
np.random.randint(5,20, 5) # array with 5 random numbers between 5 to 20

array([ 7, 10, 10,  8,  6])

## **Reshape**

In [29]:
array = np.random.randint(1,100,25)
array

array([50, 56, 49, 66, 33, 77, 58, 98, 48, 82, 13, 51, 59, 34, 63, 55, 15,
       56, 27, 92, 34, 77, 88, 17, 94])

In [32]:
matrix = array.reshape(5,5) # rows * columns = total array elements
matrix

array([[50, 56, 49, 66, 33],
       [77, 58, 98, 48, 82],
       [13, 51, 59, 34, 63],
       [55, 15, 56, 27, 92],
       [34, 77, 88, 17, 94]])

## **Max and Mins**

In [34]:
array = np.random.randint(1,100,50)
array

array([43, 55, 86,  8, 29, 41, 83, 72, 22, 54, 90, 78, 64, 42, 86, 18,  5,
       89, 40, 94, 18, 61, 40, 41, 70, 17, 20, 47, 45, 12, 80, 15, 58, 43,
       60, 53, 22, 83,  3, 36, 39, 74, 97, 89, 11, 71, 91, 42,  8, 99])

In [35]:
max_value = array.max()
max_value

99

In [36]:
pos_max_value = array.argmax()
pos_max_value

49

In [37]:
min_value = array.min()
min_value

3

In [38]:
pos_min_value = array.argmin()
pos_min_value

38

## **One dimension arrays**

In [40]:
array = np.arange(0,10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
array[5]

5

In [42]:
array[-1] # last position

9

In [44]:
array[2:4] # positin from 2 to (4 - 1)

array([2, 3])

In [45]:
array[5:] # from position 5 to last

array([5, 6, 7, 8, 9])

In [46]:
array[:4]# from begining to position 5

array([0, 1, 2, 3])

In [47]:
array2 = array.copy()
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## **Two dimension arrays**

In [49]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
matrix[0]

array([1, 2, 3])

In [51]:
matrix[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
matrix[0][0]

1

In [53]:
matrix[0,0]

1

In [54]:
matrix[:, 1]

array([2, 5, 8])

## **Conditional Selects**

In [55]:
array = np.arange(0,10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
elements_greater_than_5 = array > 5
elements_greater_than_5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [58]:
array[elements_greater_than_5]

array([6, 7, 8, 9])

In [61]:
array[ array < 5]

array([0, 1, 2, 3, 4])

In [62]:
array[ array % 2 == 0]

array([0, 2, 4, 6, 8])

## **Operations with arrays**

In [63]:
array = np.arange(0,10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
array + array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [65]:
array - array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [66]:
array * 100

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [67]:
array + 40

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [69]:
array2 = np.arange(5,15)
array2

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [70]:
array2 - array

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [71]:
np.sqrt(array2)

array([2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739])

In [72]:
np.max(array)

9